event_start: '2012-02-02T09:00:00+02:00'

participants:
#  - pawski
#  - blnight
#  - bliebek
#  - teon
  - radoslawhryciow
#  - agapy
#  - yghern
#  - afterdesign
#  - redhandpl
  - slawekp
#  - spo0lsh
#  - JoannaTrelaZielinska
#  - she11c0de
#  - grzr
#  - lklimek
  - jordansissel
  - jdalton
  - weierophinney
  - brianchandotcom
  - kevinsawicki
  - passy
