event_start: '2014-04-24T09:00:00+02:00'

participants:
#  - pawski
#  - blnight
#  - bliebek
#  - teon
#  - radoslawhryciow
  - agapy
#  - yghern
#  - afterdesign
#  - redhandpl
#  - slawekp
#  - spo0lsh
#  - JoannaTrelaZielinska
#  - she11c0de
#  - grzr
#  - lklimek
